version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Adjust this if package.json is in a subfolder (e.g., "server/" or "client/")
    schedule:
      interval: "weekly"  # Can be daily, weekly, or monthly
    open-pull-requests-limit: 5
