name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Use 'master' since you have only one branch
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Use Node.js 20 LTS if needed

      - name: Install Dependencies (Backend + Frontend)
        run: npm install

      - name: Run Backend Tests
        run: npm test  # Runs Jest tests for Express backend

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Run Frontend Tests
        run: |
          cd client
          npm test  # Runs React Testing Library tests
